name: Build Tweak
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: theos/github-action@main
        with:
          sdk: iphoneos15.2
          make-args: clean package
